import org.gradle.api.artifacts.component.ProjectComponentIdentifier
import org.gradle.api.attributes.Bundling
import org.gradle.api.attributes.Category
import org.gradle.api.attributes.LibraryElements
import org.gradle.api.attributes.Usage
import org.gradle.api.plugins.JavaApplication
import java.security.MessageDigest

plugins {
    application
    id("velocity-ctd-publish")
    id("velocity-init-manifest")
}

application {
    mainClass.set("com.velocityctd.bootstrap.BootstrapMain")
}

val proxyProject = project(":velocity-proxy")
val apiProject = project(":velocity-api")
val nativeProject = project(":velocity-native")
val permissionIntegrationSpiProject = project(":velocity-permission-integration-spi")
val configurate3Project = project(":deprecated-configurate3")

evaluationDependsOn(proxyProject.path)
val proxyMainClass = proxyProject.extensions.getByType(JavaApplication::class.java).mainClass

// Resolves the proxy's full runtime classpath (the proxy jar plus every transitive runtime
// dependency) into this project, so we can enumerate the libraries the bootstrap must ship without
// resolving another project's configuration at execution time.
val proxyRuntimeClasspath: Configuration by configurations.creating {
    isCanBeResolved = true
    isCanBeConsumed = false
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage::class.java, Usage.JAVA_RUNTIME))
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category::class.java, Category.LIBRARY))
        attribute(
            LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE,
            objects.named(LibraryElements::class.java, LibraryElements.JAR)
        )
        attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling::class.java, Bundling.EXTERNAL))
    }
}

dependencies {
    add(proxyRuntimeClasspath.name, project(":velocity-proxy"))
}

// The list of Maven repositories the bootstrap will try, in order, at runtime.
// Should be kept in sync with the repositories declared in settings.gradle.kts.
val runtimeRepositories = listOf(
    "https://repo1.maven.org/maven2",
    "https://repo.papermc.io/repository/maven-public",
    "https://repo.velocityctd.com/releases",
)

val generatedLibrariesDir = layout.buildDirectory.dir("generated/libraries")

/**
 * Generates the bootstrap library manifest (META-INF/velocityctd/libraries.list) and copies the
 * internal "jar-in-jar" modules into the bootstrap jar. External dependencies are recorded as
 * downloadable Maven artifacts (with their SHA-256), while internal modules and SNAPSHOT artifacts
 * that cannot be addressed by the standard Maven layout are embedded directly.
 */
val generateLibraries by tasks.registering {
    // The proxy is embedded as a minimal shaded jar that bundles relocated copies of the proxy's
    // `relocatedLibraries` (see :velocity-proxy:proxyRelocatedJar). Those same artifacts must be
    // excluded from the Maven manifest below.
    val proxyJar = proxyProject.tasks.named<Jar>("proxyRelocatedJar")
    val relocatedLibraries = proxyProject.configurations.getByName("relocatedLibraries")
    val apiJar = apiProject.tasks.named<Jar>("jar")
    val nativeJar = nativeProject.tasks.named<Jar>("jar")
    val permissionIntegrationSpiJar = permissionIntegrationSpiProject.tasks.named<Jar>("jar")
    val configurate3Jar = configurate3Project.tasks.named<Jar>("shadowJar")

    dependsOn(proxyJar, apiJar, nativeJar, permissionIntegrationSpiJar, configurate3Jar)

    inputs.files(proxyRuntimeClasspath)
    inputs.files(relocatedLibraries)
    inputs.files(proxyJar, apiJar, nativeJar, permissionIntegrationSpiJar, configurate3Jar)
    inputs.property("version", project.version.toString())
    inputs.property("repositories", runtimeRepositories)
    inputs.property("mainClass", proxyMainClass)

    val outputDir = generatedLibrariesDir
    outputs.dir(outputDir)

    val proxyArchive = proxyJar.flatMap { it.archiveFile }
    val apiArchive = apiJar.flatMap { it.archiveFile }
    val nativeArchive = nativeJar.flatMap { it.archiveFile }
    val permissionIntegrationSpiArchive = permissionIntegrationSpiJar.flatMap { it.archiveFile }
    val configurate3Archive = configurate3Jar.flatMap { it.archiveFile }
    val projectVersion = project.version.toString()
    val mainClassProvider = proxyMainClass

    doLast {
        val root = outputDir.get().asFile
        val jarInJarDir = root.resolve("jar-in-jar").apply {
            deleteRecursively()
            mkdirs()
        }
        val manifestFile = root.resolve("META-INF/velocityctd/libraries.list")
        manifestFile.parentFile.mkdirs()

        val lines = mutableListOf<String>()
        lines += "# Generated by :velocity-bootstrap:generateLibraries. Do not edit."
        lines += "main-class\t${mainClassProvider.get()}"
        runtimeRepositories.forEach { lines += "repo\t$it" }

        // Embed an internal module jar as a jar-in-jar and record an EMBEDDED manifest line.
        fun embed(group: String, name: String, version: String, source: File) {
            val fileName = "$name-$version.jar"
            val target = jarInJarDir.resolve(fileName)
            source.copyTo(target, overwrite = true)
            val resource = "jar-in-jar/$fileName"
            lines += listOf(
                "dep", "EMBEDDED", group, name, version, "jar", "-", sha256(target), resource
            ).joinToString("\t")
        }

        embed("com.velocityctd", "velocity-proxy", projectVersion, proxyArchive.get().asFile)
        embed("com.velocityctd", "velocity-api", projectVersion, apiArchive.get().asFile)
        embed("com.velocityctd", "velocity-native", projectVersion, nativeArchive.get().asFile)
        embed(
            "com.velocityctd", "velocity-permission-integration-spi", projectVersion,
            permissionIntegrationSpiArchive.get().asFile
        )
        embed(
            "com.velocityctd", "velocity-deprecated-configurate3", projectVersion,
            configurate3Archive.get().asFile
        )

        // Artifacts (and their transitives) that the proxy ships relocated inside its own jar. These
        // must never be downloaded from Maven.
        val relocatedKeys = relocatedLibraries.resolvedConfiguration.resolvedArtifacts
            .map { "${it.moduleVersion.id.group}:${it.moduleVersion.id.name}" }
            .toSet()

        val resolved = proxyRuntimeClasspath.resolvedConfiguration.resolvedArtifacts
        for (artifact in resolved) {
            if (artifact.id.componentIdentifier is ProjectComponentIdentifier) {
                continue
            }

            val id = artifact.moduleVersion.id

            if ("${id.group}:${id.name}" in relocatedKeys) {
                continue
            }
            val classifier = artifact.classifier ?: "-"
            val extension = artifact.extension ?: "jar"

            if (id.version.endsWith("-SNAPSHOT")) {
                val classifierSuffix = if (classifier == "-") "" else "-$classifier"
                val fileName = "${id.name}-${id.version}$classifierSuffix.$extension"
                val target = jarInJarDir.resolve(fileName)
                artifact.file.copyTo(target, overwrite = true)
                lines += listOf(
                    "dep", "EMBEDDED", id.group, id.name, id.version, extension, classifier,
                    sha256(target), "jar-in-jar/$fileName"
                ).joinToString("\t")
            } else {
                lines += listOf(
                    "dep", "MAVEN", id.group, id.name, id.version, extension, classifier,
                    sha256(artifact.file)
                ).joinToString("\t")
            }
        }

        manifestFile.writeText(lines.joinToString("\n", postfix = "\n"))
    }
}

tasks.processResources {
    from(generateLibraries)
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.velocityctd.bootstrap.BootstrapMain"
        attributes["Implementation-Title"] = "ApiaryProxy Bootstrap"
        attributes["Implementation-Vendor"] = "ApiaryProxy Contributors"
        attributes["Multi-Release"] = "true"
        attributes["Enable-Native-Access"] = "ALL-UNNAMED"
        attributes["Enable-Final-Field-Mutation"] = "ALL-UNNAMED"
    }
}

fun sha256(file: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    file.inputStream().use { input ->
        val buffer = ByteArray(8192)
        while (true) {
            val read = input.read(buffer)
            if (read < 0) {
                break
            }
            digest.update(buffer, 0, read)
        }
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}
