version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "org.yaml:snakeyaml"
      - dependency-name: "org.spongepowered:configurate-hocon"
        versions: ["3.x"]
      - dependency-name: "org.spongepowered:configurate-yaml"
        versions: ["3.x"]
      - dependency-name: "org.spongepowered:configurate-gson"
        versions: ["3.x"]