blank_issues_enabled: true
contact_links:
  - name: ApiaryProxy Issues
    url: https://github.com/ssquadteam/ApiaryProxy/issues
    about: If you are having issues with the proxy, found an exploit or have other minor issues, open an issue here.
